version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: "America/New_York"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
      time: "08:00"
      timezone: "America/New_York"
    ignore:
      - dependency-name: amazon/aws-cli
        update-types: ["version-update:semver-major"]
